version: '3.8'

services:
  service-discovery:
    build:
      context: .
      dockerfile: ServiceDiscovery/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - microservices-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  product-service:
    build:
      context: .
      dockerfile: ProductService/Dockerfile
    ports:
      - "5001:5001"
    environment:
      - ServiceDiscoveryUrl=http://service-discovery:5000
      - ASPNETCORE_URLS=http://+:5001
    depends_on:
      service-discovery:
        condition: service_healthy
    networks:
      - microservices-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5001/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  order-service:
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    ports:
      - "5002:5002"
    environment:
      - ServiceDiscoveryUrl=http://service-discovery:5000
      - ASPNETCORE_URLS=http://+:5002
    depends_on:
      service-discovery:
        condition: service_healthy
    networks:
      - microservices-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5002/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

  api-gateway:
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "5003:5003"
    environment:
      - ServiceDiscoveryUrl=http://service-discovery:5000
      - ASPNETCORE_URLS=http://+:5003
    depends_on:
      service-discovery:
        condition: service_healthy
      product-service:
        condition: service_healthy
      order-service:
        condition: service_healthy
    networks:
      - microservices-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5003/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

networks:
  microservices-network:
    driver: bridge
